version: "3.1"
services:
  nodejs-ts-boilerplate:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app/
      - ./node_modules:/app/node_modules/
